### ISSUE TITLE
Is DisMAP Toolbox zip file missing?

### ISSUE THREAD

**Issue by WMRobin** [nmfs-fish-tools/DisMAP#6]
Step 2 in the the `Readme.md` documentation of the folder `DisMAP/ArcGIS-Analysis-Python` says "Copy/Move and extract the DisMAP Toolbox Zip file into the Project Folder." However, there is no file with this name -- is this toolbox downloaded somewhere else? If it is located somewhere outside of the repo, should there be a link to this zip file?

**Comment by k-doering-NOAA** [comment]
@Melissa-Karp, is this something you could help with?

**Comment by Melissa-Karp** [comment]
Hi! we have had some difficulties getting the ArcGIS files up on github and will work to address that issue and get the necessary folder structure and scripts up on this github in the near future. Also, the zip file that is being referred to is created as part of the [create_data_for_map_generation.R](https://github.com/nmfs-fish-tools/DisMAP/blob/main/data_processing_rcode/code/create_data_for_map_generation.R) script during the data processing part of this analysis. That step generates the csv files that are output into the python subfolder under the outputs folder, and are then zipped up and send to the ArcGIS analyst for the interpolated biomass analysis. We won't include the data outputs in the repo due to data size limits, but you can generate that data following the steps in the data processing rcode.

**Comment by WMRobin** [comment]
@Melissa-Karp Thanks a lot for your response! If I understand correctly, the "DisMAP Toolbox Zip" file refers to the set of CSV files created in the R script you reference -- is that the case?

**Comment by Melissa-Karp** [comment]
Hi @WMRobin, I just clarified with our ArcGIS analyst, and I was mistaken. He provided me this clarification: " The Readme is outdated and references a zip file that contains an ArcGIS Toolbox that could be loaded and used in ArcGIS Pro. Building all the functionality into the Toolbox proved difficult and so he went back to just Python scripts." We are hoping to have the updated python scripts for the ArcGIS analysis posted to the Repo early January. Apologies for the confusion.

**Comment by WMRobin** [comment]
@Melissa-Karp Makes sense -- thank you!
